language: node_js
node_js:
- 8.7.0
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token:
    secure: aDuHhO27S+JoYf64U6+/R7jHI66G1TFj1TVs0WTR9wytXsmOoEGRYyAjX1CJM94bqqxbNOIzzWyIDl2FBCQfk+tIG6cN7UeKHj9sjFE0+aMOBzH3hTUgd7Yv7axESimhTRuNGl3N1lyqyF5NV5EnmeaBy8DkuaEfAV6tRN8bSCw/+wockcdPJiqAjeNASZYu4HwgrL1SvZaRFdkcGgtxFGxTSLagPEB+vByTjZUao95lLWyiuELSogxqKh/TwdQB+QInGvACWyWW1itR9ZdIb55QPwT12yeiR3Af2cZnjYCTTrDOgbsIOqs1DR+vOFZ9FUY8pu3BTnnnxunIcfxSmPiyDOa9ZvlglpewC5tqQtYAd6p5HBAVBn4nXS44yuAl8QkzhHF5eVF5h0znVqASWw7DZ57Yks9VpeIKIiqwJCL3YJbRB3l31U++AjBYxK8XlwlpXgTQsZJJQCdT3sR5inmDqkAJ3kBxh2cymE145Ycl/ZZFCSgL3FilXAfA9EWCSFEZ6BVFQbgSozwSAYqVOKCQQx/6vjHkXWGKLYF5xCJ72Vj5esn1HjYJjRBixsDmuFXYngwUOTjDLjeCgOtpluAHN75o1MbjcQH/zTQ/HKkrrtPZTP5no0rPulBat4/qp4Ad/2Y+d2XLOj6nwmyccxWhelU3lwuPspvrH0/ZrS8=
  on:
    branch: master